//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_CLS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empinfo
    {
        public string EmpRollno { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Designation { get; set; }
        public string Phonenumber { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    }
}
